language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - python setup.py install
  - pip install coveralls
script:
  - nosetests --exe --with-coverage
after_success:
  - coveralls
